Repository open-mmlab/mmagic, pull requests merged in 2022-12, with the labels that each got.

#1455 [Feature] Support ray sampler for EG3D
  mmedit/models/editors/eg3d/ray_sampler.py
  tests/test_models/test_editors/test_eg3d/test_ray_sampler.py
Labels: priority/P0, kind/feature

#1458 [Feature] Add EG3D modules
  mmedit/models/editors/eg3d/eg3d_modules.py
  tests/test_models/test_editors/test_eg3d/test_eg3d_modules.py
Labels: priority/P0, kind/feature

#1464 [Feature] Support TriPlane Generator for EG3D.
  mmedit/models/editors/eg3d/eg3d_generator.py
  tests/test_models/test_editors/test_eg3d/test_eg3d_generator.py
Labels: priority/P0, kind/feature

#1234 [Feature] Support disco-diffusion text-2-image
  configs/_base_/datasets/imagenet_512.py
  configs/_base_/datasets/imagenet_64.py
  configs/disco_diffusion/README.md
  configs/disco_diffusion/disco-diffusion_adm-u-finetuned_imagenet-256x256.py
  configs/disco_diffusion/disco-diffusion_adm-u-finetuned_imagenet-512x512.py
  configs/disco_diffusion/disco-diffusion_portrait_generator_v001.py
  configs/disco_diffusion/metafile.yml
  configs/guided_diffusion/README.md
  configs/guided_diffusion/adm-u_8xb32_imagenet-512x512.py
  configs/guided_diffusion/adm-u_8xb32_imagenet-64x64.py
  configs/guided_diffusion/adm-u_ddim250_8xb32_imagenet-512x512.py
  configs/guided_diffusion/metafile.yml
  mmedit/datasets/transforms/random_degradations.py
  mmedit/models/editors/__init__.py
  mmedit/models/editors/ddim/__init__.py
  mmedit/models/editors/ddim/ddim_scheduler.py
  mmedit/models/editors/ddpm/__init__.py
  mmedit/models/editors/ddpm/ddpm_scheduler.py
  mmedit/models/editors/ddpm/denoising_unet.py
  mmedit/models/editors/disco_diffusion/__init__.py
  mmedit/models/editors/disco_diffusion/clip_wrapper.py
  mmedit/models/editors/disco_diffusion/disco.py
  mmedit/models/editors/disco_diffusion/guider.py
  mmedit/models/editors/disco_diffusion/secondary_model.py
  mmedit/models/editors/guided_diffusion/__init__.py
  mmedit/models/editors/guided_diffusion/adm.py
  mmedit/models/losses/__init__.py
  mmedit/models/losses/pixelwise_loss.py
  mmedit/models/utils/diffusion_utils.py
  mmedit/registry.py
  model-index.yml
  requirements/optional.txt
  requirements/runtime.txt
  tests/test_models/test_editors/test_disco_diffusion/test_disco_diffusion.py
Labels: status/WIP, priority/P1, kind/feature

#1498 [Fix] Support arccos in camera for torch <= 1.6
  mmedit/models/editors/eg3d/camera.py
  tests/test_models/test_editors/test_pconv/test_pconv_inpaintor.py
  tests/test_models/test_editors/test_pggan/test_pggan_discriminator.py
  tests/test_models/test_editors/test_ttsr/test_ttsr_disc.py
  tests/test_models/test_editors/test_ttsr/test_ttsr_net.py
Labels: kind/enhancement, priority/P0

#1499 [Enhanchment] Fix unit test of EG3D Render for torch < 1.8.0
  mmedit/models/editors/eg3d/renderer.py
  tests/test_models/test_editors/test_eg3d/test_camera.py
  tests/test_models/test_editors/test_eg3d/test_renderer.py
Labels: kind/enhancement, priority/P0

#1490 [Enhancement] Mock LPIPS module in PPL metric
  tests/test_evaluation/test_metrics/test_ppl.py
Labels: kind/enhancement

#1511 [Enhancement] Fix unit test for disco diffusion
  tests/test_models/test_editors/test_disco_diffusion/test_disco_diffusion.py
Labels: kind/enhancement

#1509 [Enhancement] Add torch1.13 checking in CI
  .circleci/test.yml
  .github/workflows/merge_stage_test.yml
Labels: kind/enhancement

#1514 [Enhanchement] Revise test requirements and CI
  .circleci/test.yml
  .github/workflows/merge_stage_test.yml
  .github/workflows/pr_stage_test.yml
  requirements/runtime.txt
  requirements/tests.txt
Labels: kind/enhancement

#1523 [Enhancement] Fix text2image inferencer + disco diffusion GPU test
  mmedit/models/editors/disco_diffusion/guider.py
  tests/test_apis/test_inferencers/test_text2image_inferencers.py
  tests/test_models/test_editors/test_disco_diffusion/test_disco_diffusion.py
Labels: kind/enhancement

#1524 [Feature] Support Json-annotation to `BasicConditonalDataset`
  docs/en/howto/dataset.md
  mmedit/datasets/basic_conditional_dataset.py
  tests/data/dataset/anno.json
  tests/data/dataset/wrong.yml
  tests/test_datasets/test_basic_conditional_dataset.py
Labels: kind/enhancement

#1529 revise config of biggan-cvt
  configs/biggan/biggan-deep_cvt-hugging-face_rgb_imagenet1k-256x256.py
  configs/biggan/biggan-deep_cvt-hugging-face_rgb_imagenet1k-512x512.py
Labels: kind/enhancement

#775 [Feature] Add metric module for FID and KID
  docs/en/tutorials/inception_eval.md
  mmedit/core/__init__.py
  mmedit/core/evaluation/__init__.py
  mmedit/core/evaluation/eval_hooks.py
  mmedit/core/evaluation/inception_utils.py
  mmedit/core/evaluation/inceptions.py
  mmedit/core/registry.py
  mmedit/datasets/base_sr_dataset.py
  mmedit/models/restorers/basic_restorer.py
  tests/test_metrics/test_inceptions.py
  tests/test_models/test_restorers/test_basic_restorer.py
  tests/test_runtime/test_eval_hook.py
Labels: status/WIP, priority/P1, kind/feature

#1544 [Enhancement] Revise `_base_` in tdan's config
  configs/tdan/README.md
  configs/tdan/README_zh-CN.md
  configs/tdan/metafile.yml
  configs/tdan/tdan_x4_8xb16-lr1e-4-400k_vimeo90k-bi.py
  configs/tdan/tdan_x4ft_8xb16-lr5e-5-400k_vimeo90k-bi.py
  configs/tdan/tdan_x4ft_8xb16-lr5e-5-800k_vimeo90k-bd.py
Labels: kind/enhancement

#1549 [Enhancement] Use coverage < 7.0.0 in unit tests
  requirements/tests.txt
Labels: kind/enhancement

#1550 [Fix] fix restormer ut
  tests/test_models/test_editors/test_restormer/test_restormer_net.py
Labels: kind/bug

#1536 [Enhancement] Cover more lines of cyclegan-module's unit test
  tests/test_models/test_editors/test_cyclegan/test_cyclegan_modules.py
Labels: kind/enhancement

#1528 [Enhancement] Revise SWD metric and DCGAN's configs
  configs/dcgan/dcgan_1xb128-300kiters_celeba-cropped-64.py
  configs/dcgan/dcgan_1xb128-5epoches_lsun-bedroom-64x64.py
  configs/dcgan/dcgan_Glr4e-4_Dlr1e-4_1xb128-5kiters_mnist-64x64.py
  mmedit/evaluation/metrics/base_gen_metric.py
  mmedit/evaluation/metrics/swd.py
  tests/test_evaluation/test_metrics/test_base_gen_metric.py
  tests/test_evaluation/test_metrics/test_swd.py
  tests/test_models/test_editors/test_wgan_gp/test_wgan_gp.py
  tests/test_models/test_losses/test_feature_loss.py
  tests/test_models/test_losses/test_loss_comps/test_gen_auxiliary_loss_comps.py
  tests/test_models/test_losses/test_perceptual_loss.py
Labels: kind/enhancement

#1534 [Community] Support GLIDE
  mmedit/models/editors/ddpm/denoising_unet.py
  projects/glide/configs/README.md
  projects/glide/configs/glide_ddim-classifier-free_laion-64x64.py
  projects/glide/models/__init__.py
  projects/glide/models/glide.py
  projects/glide/models/glide_modules.py
  projects/glide/models/glide_tokenizer/__init__.py
  projects/glide/models/glide_tokenizer/bpe.py
  projects/glide/models/glide_tokenizer/bpe_simple_vocab_16e6.txt.gz
  projects/glide/models/glide_tokenizer/encoder.json.gz
  projects/glide/models/glide_tokenizer/simple_tokenizer.py
  projects/glide/models/glide_tokenizer/vocab.bpe.gz
  projects/glide/models/text2im_unet.py
Labels: status/WIP, priority/P0
