Repository open-mmlab/mmagic, pull requests merged in 2022-11, with the labels that each got.

#1303 [Feature] Support qualitative comparison tools
  tools/gui/README.md
  tools/gui/component.py
  tools/gui/gui.py
  tools/gui/page_general.py
  tools/gui/page_sr.py
  tools/gui/utils.py
Labels: status/WIP, priority/P0, kind/feature

#1391 [Config] Revise Pix2Pix edges2shoes config
  configs/pix2pix/README.md
  configs/pix2pix/metafile.yml
  configs/pix2pix/pix2pix_vanilla-unet-bn_wo-jitter-flip-1xb4-190kiters_edges2shoes.py
Labels: kind/enhancement

#1392 [Bug] fix rdn and srcnn train configs
  configs/rdn/rdn_x2c64b16_1xb16-1000k_div2k.py
  configs/rdn/rdn_x3c64b16_1xb16-1000k_div2k.py
  configs/rdn/rdn_x4c64b16_1xb16-1000k_div2k.py
  configs/srcnn/srcnn_x4k915_1xb16-1000k_div2k.py
Labels: kind/bug

#1404 [Bug] fix cain config
  configs/cain/cain_g1b32_1xb5_vimeo90k-triplet.py
Labels: kind/bug

#1407 [Fix] Revise config and pretrain model loading in esrgan
  .dev_scripts/train_benchmark.py
  configs/esrgan/esrgan_psnr-x4c64b23g32_1xb16-1000k_div2k.py
  configs/esrgan/esrgan_x4c64b23g32_1xb16-400k_div2k.py
  mmedit/models/editors/esrgan/rrdb_net.py
Labels: kind/bug, priority/P0

#1408 [Enhancement] Support `try_import` for `mmdet`
  mmedit/datasets/transforms/crop.py
  mmedit/utils/__init__.py
  mmedit/utils/setup_env.py
  tests/test_utils/test_setup_env.py
Labels: kind/enhancement, priority/P0

#1420 [Enhancement] Support try-import for `clip`
  .circleci/test.yml
  .github/workflows/pr_stage_test.yml
  mmedit/models/losses/clip_loss.py
  requirements.txt
  requirements/optional.txt
  requirements/runtime.txt
Labels: kind/enhancement

#1373 [Enhancement]: Improve the rendering of Docs-API
  docs/en/.dev_scripts/update_dataset_zoo.sh
  docs/en/3_model_zoo.md
  docs/en/_static/css/readthedocs.css
  docs/en/_template/classtemplate.rst
  docs/en/api.rst
  docs/en/api/apis.rst
  docs/en/api/datasets.rst
  docs/en/api/datasets.transforms.rst
  docs/en/api/engine.hooks.rst
  docs/en/api/engine.optimizers.rst
  docs/en/api/engine.runner.rst
  docs/en/api/engine.schedulers.rst
  docs/en/api/evaluation.functional.rst
  docs/en/api/evaluation.metrics.rst
  docs/en/api/models.base_models.rst
  docs/en/api/models.data_preprocessors.rst
  docs/en/api/models.editors.rst
  docs/en/api/models.losses.rst
  docs/en/api/models.utils.rst
  docs/en/api/structures.rst
  docs/en/api/utils.rst
  docs/en/api/visualization.rst
  docs/en/conf.py
  docs/en/dataset_zoo/0_overview.md
  docs/en/dataset_zoo/1_super_resolution_datasets.md
  docs/en/dataset_zoo/2_inpainting_datasets.md
  docs/en/dataset_zoo/3_matting_datasets.md
  docs/en/dataset_zoo/4_video_interpolation_datasets.md
  docs/en/dataset_zoo/5_unconditional_gans_datasets.md
  docs/en/dataset_zoo/6_image_translation_datasets.md
  docs/en/docutils.conf
  docs/en/index.rst
Labels: info/1.x

#1430 [Enhancement] Fix 'after_test_ite' of vis hook + support 'max_save_at_test'
  mmedit/engine/hooks/visualization_hook.py
  tests/test_engine/test_hooks/test_visualization_hook.py
Labels: kind/enhancement

#1459 [Fix] Revise unit test of log processor
  tests/test_engine/test_runner/test_log_processor.py
Labels: kind/enhancement

#1444 [Feature] Support json (dict-like) annotation for BasicConditionalDataset
  docs/en/advanced_guides/2_dataset.md
  mmedit/datasets/basic_conditional_dataset.py
  tests/data/dataset/anno.json
  tests/data/dataset/wrong.yml
  tests/test_datasets/test_basic_conditional_dataset.py
Labels: priority/P0, kind/feature

#783 add 'DIM online merge config demo'
  configs/dim/dim_stage1-v16_1xb1-1000k_comp1k_online-merge.py
Labels: kind/feature

#1471 [Fix] Adopt ut with newest mmengine
  tests/test_models/test_base_models/test_two_stage.py
  tests/test_models/test_editors/test_aotgan/test_aot_inpaintor.py
  tests/test_models/test_editors/test_deepfillv2/test_two_stage_encoder_decoder.py
  tests/test_models/test_editors/test_pconv/test_pconv_inpaintor.py
Labels: kind/bug, priority/P0

#1447 [Feature] Support conditional FID for EG3D
  mmedit/evaluation/evaluator.py
  mmedit/evaluation/functional/inception_utils.py
  mmedit/evaluation/metrics/base_gen_metric.py
  mmedit/evaluation/metrics/equivariance.py
  mmedit/evaluation/metrics/fid.py
  mmedit/evaluation/metrics/inception_score.py
  mmedit/evaluation/metrics/ms_ssim.py
  mmedit/evaluation/metrics/ppl.py
  mmedit/evaluation/metrics/precision_and_recall.py
  tests/test_evaluation/test_evaluator.py
  tests/test_evaluation/test_metrics/test_base_gen_metric.py
  tests/test_evaluation/test_metrics/test_fid.py
Labels: priority/P0, kind/feature

#1446 [Feature] Support camera class for EG3D
  mmedit/evaluation/metrics/ppl.py
  mmedit/models/editors/eg3d/camera.py
  mmedit/models/utils/__init__.py
  mmedit/models/utils/tensor_utils.py
  tests/test_models/test_editors/test_eg3d/test_camera.py
  tests/test_models/test_utils/test_tensor_utils.py
Labels: priority/P0, kind/feature

#1454 [Feature] Support EG3D renderer
  mmedit/models/editors/eg3d/math_utils.py
  mmedit/models/editors/eg3d/renderer.py
  tests/test_models/test_editors/test_eg3d/test_renderer.py
Labels: priority/P0, kind/feature
