Repository open-mmlab/mmagic, pull requests merged in 2022-02, with the labels that each got.

#734 Redesign CI for Linux
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  requirements/tests.txt
Labels: CI

#714 Update commit hook copyright
  .pre-commit-config.yaml
  mmedit/datasets/pipelines/__init__.py
  mmedit/datasets/pipelines/crop.py
  mmedit/datasets/pipelines/random_degradations.py
  mmedit/models/backbones/encoder_decoders/__init__.py
  mmedit/models/backbones/encoder_decoders/aot_encoder_decoder.py
  mmedit/models/backbones/encoder_decoders/decoders/__init__.py
  mmedit/models/backbones/encoder_decoders/decoders/aot_decoder.py
  mmedit/models/backbones/encoder_decoders/encoders/__init__.py
  mmedit/models/backbones/encoder_decoders/encoders/aot_encoder.py
  mmedit/models/backbones/encoder_decoders/necks/__init__.py
  mmedit/models/backbones/encoder_decoders/necks/aot_neck.py
  mmedit/models/backbones/vfi_backbones/cain_net.py
  mmedit/models/common/downsample.py
  mmedit/models/components/discriminators/smpatch_disc.py
  mmedit/models/components/discriminators/unet_disc.py
  mmedit/models/inpaintors/aot_inpaintor.py
  mmedit/models/restorers/real_esrgan.py
  tests/test_runtime/test_ema_hook.py
  tools/deployment/test_torchserver.py
Labels: Homework

#732 Add CI for windows
  .github/workflows/build.yml
  requirements/runtime.txt
Labels: CI

#738 [Improve] Support windows path
  .dev_scripts/github/update_model_index.py
  .github/workflows/build-windows.yml
  .github/workflows/build.yml
  mmedit/apis/restoration_video_inference.py
  mmedit/datasets/pipelines/augmentation.py
  mmedit/datasets/sr_folder_multiple_gt_dataset.py
  mmedit/datasets/sr_folder_video_dataset.py
  mmedit/datasets/sr_reds_dataset.py
  mmedit/datasets/sr_test_multiple_gt_dataset.py
  mmedit/datasets/sr_vid4_dataset.py
  mmedit/datasets/sr_vimeo90k_dataset.py
  mmedit/datasets/sr_vimeo90k_multiple_gt_dataset.py
  mmedit/datasets/vfi_vimeo90k_dataset.py
  tests/test_data/test_datasets/test_sr_dataset.py
  tests/test_data/test_pipelines/test_augmentation.py
  tests/test_data/test_pipelines/test_trimap.py
  tools/data/matting/comp1k/check_extended_fg.py
  tools/data/super-resolution/reds/crop_sub_images.py
  tools/data/super-resolution/reds/preprocess_reds_dataset.py
Labels: Windows
