Repository open-mmlab/mmagic, pull requests merged in 2022-10, with the labels that each got.

#1162 [Improve] add a version option in docs menu
  docs/en/.dev_scripts/update_dataset_zoo.sh
  docs/en/3_model_zoo.md
  docs/en/conf.py
  docs/en/dataset_zoo/0_overview.md
  docs/en/dataset_zoo/1_super_resolution_datasets.md
  docs/en/dataset_zoo/2_inpainting_datasets.md
  docs/en/dataset_zoo/3_matting_datasets.md
  docs/en/dataset_zoo/4_video_interpolation_datasets.md
  docs/en/dataset_zoo/5_unconditional_gans_datasets.md
  docs/en/dataset_zoo/6_image_translation_datasets.md
  docs/zh_cn/conf.py
Labels: enhancement, P1

#1164 [Enhance] update dev_scripts for link checking
  .dev_scripts/README.md
  .dev_scripts/doc_link_checker.py
Labels: enhancement, P1

#1163 [Enhancement] add version switcher to the docs menu
  docs/en/conf.py
  docs/zh_cn/conf.py
Labels: enhancement, P1

#1161 [Refactoring] decompose the implementations of different metrics into several files
  mmedit/evaluation/metrics/__init__.py
  mmedit/evaluation/metrics/connectivity_error.py
  mmedit/evaluation/metrics/gradient_error.py
  mmedit/evaluation/metrics/mae.py
  mmedit/evaluation/metrics/matting.py
  mmedit/evaluation/metrics/matting_mse.py
  mmedit/evaluation/metrics/metrics_utils.py
  mmedit/evaluation/metrics/mse.py
  mmedit/evaluation/metrics/pixel_metrics.py
  mmedit/evaluation/metrics/psnr.py
  mmedit/evaluation/metrics/sad.py
  mmedit/evaluation/metrics/snr.py
  tests/test_evaluation/test_metrics/test_connectivity_error.py
  tests/test_evaluation/test_metrics/test_gradient_error.py
  tests/test_evaluation/test_metrics/test_mae.py
  tests/test_evaluation/test_metrics/test_matting_mse.py
  tests/test_evaluation/test_metrics/test_metrics_utils.py
  tests/test_evaluation/test_metrics/test_mse.py
  tests/test_evaluation/test_metrics/test_pixel_metrics.py
  tests/test_evaluation/test_metrics/test_psnr.py
  tests/test_evaluation/test_metrics/test_sad.py
  tests/test_evaluation/test_metrics/test_snr.py
Labels: Refactoring, P1

#1172 [Fix] Fix PPL bug
  mmedit/evaluation/metrics/ppl.py
  mmedit/utils/io_utils.py
Labels: Bug:P0

#1256 [Docs] Update 3-new-model.yml
  .github/ISSUE_TEMPLATE/3-new-model.yml
Labels: docs

#1262 [Fix] fix restoration_video_demo bug
  mmedit/apis/restoration_video_inference.py
Labels: bug, WIP, P0

#1167 [Fix] Fix bugs in `sr test config`, `realbasicvsr config` and `pconv config`
  configs/_base_/datasets/sisr_x2_test_config.py
  configs/_base_/datasets/sisr_x3_test_config.py
  configs/_base_/datasets/sisr_x4_test_config.py
  configs/partial_conv/pconv_stage1_8xb1_celeba-256x256.py
  configs/real_basicvsr/realbasicvsr_wogan-c64b20-2x30x8_8xb2-lr1e-4-300k_reds.py
Labels: bug, WIP, P0

#1292 [Bug Fixed] Correct the number of output channels of LFF in RDB
  mmedit/models/backbones/sr_backbones/rdn.py
Labels: bug, awaiting response, P0

#1171 [Feature] Support multi-metrics with different sample-model
  mmedit/evaluation/evaluator.py
  tests/test_evaluation/test_evaluator.py
Labels: kind/bug, status/WIP, priority/P0

#1286 [Enhancement] improve issue template
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/2-feature-request.yml
  .github/ISSUE_TEMPLATE/3-new-model.yml
  .github/ISSUE_TEMPLATE/4-documentation.yml
Labels: kind/enhancement, status/WIP, priority/P0

#1302 [Fix] fix GenerateSegmentIndices ut
  tests/test_datasets/test_transforms/test_generate_frame_indices.py
Labels: kind/enhancement, status/WIP, priority/P0

#1306 [Enhancement] Reduce the randomness in unit test of `stylegan3_utils.py`
  tests/test_models/test_editors/test_stylegan3/test_stylegan3_utils.py
Labels: kind/enhancement, status/WIP, priority/P0

#1320 [CI] Fix GitHub windows CI
  .github/workflows/merge_stage_test.yml
  .github/workflows/pr_stage_test.yml
Labels: kind/bug, priority/P0

#1300 [Fix] fix vsr models pytorch2onnx
  tools/model_converters/pytorch2onnx.py
Labels: kind/bug, status/WIP, priority/P0

#1310 [Bug] Ensure the output type of `GenerateFacialHeatmap` is `np.float32`
  mmedit/datasets/transforms/generate_assistant.py
Labels: kind/bug, priority/P0

#1308 [Bug] Fix sampling behavior of `unpaired_dataset.py` and urls in cyclegan's README
  configs/_base_/datasets/unpaired_imgs_256x256.py
  configs/cyclegan/README.md
  configs/cyclegan/cyclegan_lsgan-id0-resnet-in_1xb1-250kiters_summer2winter.py
  configs/cyclegan/cyclegan_lsgan-id0-resnet-in_1xb1-270kiters_horse2zebra.py
  configs/cyclegan/cyclegan_lsgan-id0-resnet-in_1xb1-80kiters_facades.py
  configs/cyclegan/cyclegan_lsgan-resnet-in_1xb1-250kiters_summer2winter.py
  configs/cyclegan/cyclegan_lsgan-resnet-in_1xb1-270kiters_horse2zebra.py
  configs/cyclegan/cyclegan_lsgan-resnet-in_1xb1-80kiters_facades.py
  configs/cyclegan/metafile.yml
  mmedit/datasets/unpaired_image_dataset.py
Labels: kind/bug, priority/P0

#1325 [README] Fix TTSR's README
  configs/ttsr/README.md
  configs/ttsr/metafile.yml
Labels: priority/P0, kind/doc

#1327 [CI] Update `paths-ignore` for GitHub CI
  .github/workflows/merge_stage_test.yml
  .github/workflows/pr_stage_test.yml
Labels: kind/enhancement, priority/P1

#1326 [Doc] update docstring of RDN
  mmedit/models/backbones/sr_backbones/rdn.py
Labels: priority/P1, kind/doc

#1328 [Bug] Save gt images in PGGAN's `forward`
  mmedit/models/editors/pggan/pggan.py
  tests/test_models/test_editors/test_pggan/test_pggan.py
Labels: kind/bug, priority/P0

#1331 [Bug] Revise flip transformation in some conditional gan's setting
  configs/_base_/datasets/cifar10_nopad.py
  configs/_base_/datasets/imagenet_128.py
Labels: kind/bug, priority/P0

#1335 [Unit Test] Fix unit test of SNR
  tests/test_evaluation/test_metrics/test_snr.py
Labels: kind/enhancement, priority/P1

#1336 [Bug] Revise flavr config
  configs/flavr/flavr_in4out1_8xb4_vimeo90k-septuplet.py
Labels: kind/bug

#1341 [Fix] fix realesrgan ema
  configs/real_esrgan/realesrgan_c64b23g32_4xb12-lr1e-4-400k_df2k-ost.py
  configs/real_esrgan/realesrnet_c64b23g32_4xb12-lr2e-4-1000k_df2k-ost.py
  mmedit/models/editors/real_basicvsr/real_basicvsr.py
  mmedit/models/editors/real_esrgan/real_esrgan.py
  tests/test_models/test_editors/test_real_esrgan/test_real_esrgan.py
Labels: kind/bug, priority/P0

#1352 [Config] Revise discriminator's learning rate of TTSR to align with 0.x version
  configs/ttsr/ttsr-gan_x4c64b16_1xb9-500k_CUFED.py
Labels: kind/bug

#1367 [Fix] fix edsr configs
  configs/edsr/edsr_x2c64b16_1xb16-300k_div2k.py
  configs/edsr/edsr_x3c64b16_1xb16-300k_div2k.py
  configs/edsr/edsr_x4c64b16_1xb16-300k_div2k.py
Labels: kind/bug

#1365 [Enhancement] Add pixel value clip in visualizer
  mmedit/visualization/gen_visualizer.py
Labels: kind/enhancement, priority/P0

#1364 [Bug] Fix randomness in FixedCrop + add L1 loss in Pix2Pix
  configs/_base_/datasets/paired_imgs_256x256_crop.py
  configs/_base_/models/base_pix2pix.py
  configs/pix2pix/pix2pix_vanilla-unet-bn_1xb1-220kiters_aerial2maps.py
  configs/pix2pix/pix2pix_vanilla-unet-bn_1xb1-220kiters_maps2aerial.py
  configs/pix2pix/pix2pix_vanilla-unet-bn_1xb1-80kiters_facades.py
  configs/pix2pix/pix2pix_vanilla-unet-bn_wo-jitter-flip-4xb1-190kiters_edges2shoes.py
  mmedit/models/base_models/base_translation_model.py
  mmedit/models/editors/pix2pix/pix2pix.py
Labels: kind/bug, priority/P0

#1358 [Fix] fix realbasicvsr config
  configs/real_basicvsr/realbasicvsr_c64b20-1x30x8_8xb1-lr5e-5-150k_reds.py
  configs/real_basicvsr/realbasicvsr_wogan-c64b20-2x30x8_8xb2-lr1e-4-300k_reds.py
Labels: kind/bug

#1363 [Enhancement] Fix PESinGAN-inter-pad setting + add SinGAN Dataset + add SinGAN demo
  configs/singan/singan_fish.py
  demo/singan_demo.py
  mmedit/datasets/__init__.py
  mmedit/datasets/singan_dataset.py
  mmedit/datasets/transforms/formatting.py
  mmedit/models/editors/mspie/pe_singan_generator.py
  mmedit/models/editors/singan/singan.py
  tests/test_datasets/test_singan_dataset.py
  tests/test_datasets/test_transforms/test_formatting.py
  tests/test_models/test_editors/test_mspie/test_pe_singan_generator.py
  tests/test_models/test_editors/test_singan/test_singan.py
Labels: kind/bug, priority/P0, kind/feature

#1372 [Fix] fix types of exceptions in demos
  mmedit/apis/restoration_video_inference.py
  mmedit/apis/video_interpolation_inference.py
Labels: info/1.x

#1356 [Enhancement] Support deterministic training in benchmark
  .dev_scripts/README.md
  .dev_scripts/train_benchmark.py
Labels: kind/enhancement

#1375 [Enhancement] Rename VisualizationHook to MMEditVisualizationHook
  configs/inpainting/AOT-GAN/AOT-GAN_512x512_4x12_places.py
  configs/inpainting/deepfillv1/deepfillv1_256x256_4x4_celeba.py
  configs/inpainting/deepfillv1/deepfillv1_256x256_8x2_places.py
  configs/inpainting/deepfillv2/deepfillv2_256x256_8x2_celeba.py
  configs/inpainting/deepfillv2/deepfillv2_256x256_8x2_places.py
  configs/inpainting/global_local/gl_256x256_8x12_celeba.py
  configs/inpainting/global_local/gl_256x256_8x12_places.py
  configs/inpainting/partial_conv/pconv_256x256_stage1_8x1_celeba.py
  configs/inpainting/partial_conv/pconv_256x256_stage1_8x1_places.py
  configs/inpainting/partial_conv/pconv_256x256_stage2_4x2_celeba.py
  configs/inpainting/partial_conv/pconv_256x256_stage2_4x2_places.py
  docs/en/configs/config_inpainting.md
  docs/zh_cn/configs/config_inpainting.md
  mmedit/core/__init__.py
  mmedit/core/hooks/__init__.py
  mmedit/core/hooks/visualization.py
  mmedit/utils/__init__.py
  mmedit/utils/misc.py
  tests/test_runtime/test_visual_hook.py
  tests/test_utils/test_misc.py
Labels: kind/enhancement

#1385 [Fix] Avoid cast int and float in GenDataPreprocessor
  mmedit/models/data_preprocessors/gen_preprocessor.py
Labels: kind/bug, priority/P0

#1386 [Config] Update metric config in ggan
  configs/_base_/datasets/paired_imgs_256x256_crop.py
  configs/_base_/datasets/unpaired_imgs_256x256.py
  configs/_base_/gen_default_runtime.py
  configs/_base_/matting_default_runtime.py
  configs/ggan/ggan_dcgan-archi_lr1e-3-1xb128-12Mimgs_celeba-cropped-64x64.py
  configs/ggan/ggan_dcgan-archi_lr1e-4-1xb64-10Mimgs_celeba-cropped-128x128.py
Labels: kind/enhancement, priority/P0

#1380 [Fix]: add type and change default number of preprocess_div2k_dataset.py
  tools/dataset_converters/super-resolution/div2k/preprocess_div2k_dataset.py
Labels: info/1.x
