Repository open-mmlab/mmagic, pull requests merged in 2022-03, with the labels that each got.

#740 bump to v0.13.0
  README.md
  README_zh-CN.md
  docs/en/changelog.md
  docs/zh_cn/changelog.md
  mmedit/version.py
Labels: Homework

#725 Rearrange requirements.txt
  .github/workflows/build-windows.yml
  .github/workflows/build.yml
  requirements.txt
  requirements/optional.txt
  requirements/runtime.txt
  setup.py
Labels: CI

#779 [Docs] Add Tutorial of pipeline
  docs/en/index.rst
  docs/en/tutorials/customize_pipeline.md
  docs/en/tutorials/index.rst
Labels: size/XS

#778 [Doc] Update BasicVSR++ and RealBasicVSR docs
  README.md
  README_zh-CN.md
  configs/restorers/basicvsr_plusplus/README.md
  configs/restorers/basicvsr_plusplus/README_zh-CN.md
  configs/restorers/real_basicvsr/README.md
  configs/restorers/real_basicvsr/README_zh-CN.md
Labels: size/XS

#782 Update link in README
  README.md
  README_zh-CN.md
Labels: size/XS

#785 [Docs] Update citation
  CITATION.cff
  README.md
  README_zh-CN.md
Labels: size/XS

#787 [Docs] clear additional comments in citation.cff
  CITATION.cff
Labels: size/XS

#793 [Enhance] Support gray normalization constant in EDSR
  configs/restorers/edsr/edsr_x2c64b16_g1_300k_div2k.py
  configs/restorers/edsr/edsr_x3c64b16_g1_300k_div2k.py
  configs/restorers/edsr/edsr_x4c64b16_g1_300k_div2k.py
  mmedit/models/backbones/sr_backbones/edsr.py
  tests/test_models/test_backbones/test_sr_backbones/test_sr_backbones.py
Labels: size/XS

#791 [Enhance] Support dist_train without slurm
  docs/en/quick_run.md
  docs/zh_cn/quick_run.md
  tools/dist_test.sh
  tools/dist_train.sh
Labels: size/XS

#798 Use full name of config as 'Name' in metafile
  .dev_scripts/github/update_model_index.py
  configs/inpainting/deepfillv1/metafile.yml
  configs/inpainting/deepfillv2/metafile.yml
  configs/inpainting/global_local/metafile.yml
  configs/inpainting/partial_conv/metafile.yml
  configs/mattors/dim/metafile.yml
  configs/mattors/gca/metafile.yml
  configs/mattors/indexnet/metafile.yml
  configs/restorers/basicvsr/metafile.yml
  configs/restorers/basicvsr_plusplus/metafile.yml
  configs/restorers/dic/metafile.yml
  configs/restorers/edsr/metafile.yml
  configs/restorers/edvr/metafile.yml
  configs/restorers/esrgan/metafile.yml
  configs/restorers/glean/metafile.yml
  configs/restorers/iconvsr/metafile.yml
  configs/restorers/liif/metafile.yml
  configs/restorers/rdn/metafile.yml
  configs/restorers/real_basicvsr/metafile.yml
  configs/restorers/real_esrgan/metafile.yml
  configs/restorers/srcnn/metafile.yml
  configs/restorers/srresnet_srgan/metafile.yml
  configs/restorers/tdan/metafile.yml
  configs/restorers/tof/metafile.yml
  configs/restorers/ttsr/metafile.yml
  configs/synthesizers/cyclegan/metafile.yml
  configs/synthesizers/pix2pix/metafile.yml
  configs/video_interpolators/cain/metafile.yml
Labels: size/XXL

#800 [Docs] Add brief installation steps in README(_zh-CN).md
  README.md
  README_zh-CN.md
Labels: size/XS

#788 [Docs] Regroup docs
  docs/en/config.md
  docs/en/faq.md
  docs/en/index.rst
  docs/en/tutorials/customize_models.md
Labels: size/XS

#790 [Feature] Support streaming reading of frames in video interpolation demo
  demo/video_interpolation_demo.py
  mmedit/apis/video_interpolation_inference.py
  mmedit/models/video_interpolators/basic_interpolator.py
  tests/test_inference.py
Labels: size/XS

#786 [Fix] Update pre-trained SPyNet path in RealBasicVSR config
  configs/restorers/real_basicvsr/realbasicvsr_c64b20_1x30x8_lr5e-5_150k_reds.py
  configs/restorers/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds.py
Labels: size/XS

#795 [Fix] Fix matting tutorial, and fix links to colab
  demo/matting_tutorial.ipynb
  demo/restorer_basic_tutorial.ipynb
  demo/restorer_basic_tutorial_zh-CN.ipynb
Labels: size/XS

#792 [Enhance] Put LQ into CPU for restoration_video_demo
  mmedit/apis/restoration_video_inference.py
Labels: size/XS

#801 [Fix] Update preprocess_div2k_dataset.py
  tools/data/super-resolution/div2k/preprocess_div2k_dataset.py
Labels: size/XS

#812 [Docs] Fix Y/GRB mistake in EDSR README
  configs/restorers/edsr/README.md
Labels: size/XS

#805 [Improve] Add `clamp(0, 1)` in test
  mmedit/models/video_interpolators/basic_interpolator.py
  tests/test_models/test_video_interpolator/test_basic_interpolator.py
Labels: size/XS

#807 [Fix] Update SR Colab Demo Installation Method and Set5 link
  demo/restorer_basic_tutorial.ipynb
  demo/restorer_basic_tutorial_zh-CN.ipynb
Labels: size/XS

#781 [Feature] Use `--diff-seed` to set different torch seed on different rank
  mmedit/apis/__init__.py
  mmedit/apis/train.py
  mmedit/datasets/builder.py
  tests/test_runtime/test_apis.py
  tools/train.py
Labels: size/XS

#799 [Fix] `flip_ratio` in `RandomAffine` pipeline is inverted
  mmedit/datasets/pipelines/augmentation.py
  tests/test_data/test_pipelines/test_augmentation.py
Labels: size/XS

#813 [Docs] make `dataset.pipeline` a dedicated section in doc
  docs/en/api.rst
  docs/zh_cn/api.rst
Labels: size/XS

#819 fix model zoo link
  README.md
Labels: size/XS

#808 [Fix] use hyphen for command line args in demo & tools
  demo/generation_demo.py
  demo/inpainting_demo.py
  demo/matting_demo.py
  demo/restoration_demo.py
  demo/restoration_face_demo.py
  demo/restoration_video_demo.py
  demo/video_interpolation_demo.py
  docs/en/demo.md
  docs/en/getting_started.md
  docs/zh_cn/demo.md
  docs/zh_cn/getting_started.md
  mmedit/utils/__init__.py
  mmedit/utils/cli.py
  tests/test_utils/test_modify_args.py
  tools/data/matting/comp1k/README.md
  tools/data/matting/comp1k/README_zh-CN.md
  tools/data/matting/comp1k/preprocess_comp1k_dataset.py
  tools/data/super-resolution/vimeo90k/README.md
  tools/data/super-resolution/vimeo90k/README_zh-CN.md
  tools/data/super-resolution/vimeo90k/preprocess_vimeo90k_dataset.py
  tools/evaluate_comp1k.py
Labels: size/XS

#820 [Fix] Fix link in basicvsr_plusplus
  configs/restorers/basicvsr_plusplus/README.md
  configs/restorers/basicvsr_plusplus/README_zh-CN.md
  configs/restorers/basicvsr_plusplus/metafile.yml
Labels: size/XS

#822 [Fix] Use underline for required aruments in python files.
  demo/generation_demo.py
  demo/inpainting_demo.py
  demo/matting_demo.py
  demo/restoration_face_demo.py
  demo/restoration_video_demo.py
  demo/video_interpolation_demo.py
  tools/evaluate_comp1k.py
Labels: size/XS

#816 [Fix] Replace pytorch install command to conda in README(_zh-CN).md
  README.md
  README_zh-CN.md
Labels: Homework
